---
name: CI
permissions: {}

on: [ push ]
jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        javaVersion: [ 11, 17, 21 ]
        javaDistribution: [ "temurin", "zulu" ]
    name: Java ${{ matrix.javaVersion }}-${{ matrix.javaDistribution }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: ${{ matrix.javaDistribution }}
          java-version: ${{ matrix.javaVersion }}
      - uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Verify with Maven
        if: ${{ matrix.javaVersion >= 17 }}
        run: mvn verify --no-transfer-progress -Drevision=0.1.0 -Dchangelist=-SNAPSHOT
      - name: Verify with Maven
        if: ${{ matrix.javaVersion < 17 }}
        run: mvn verify --no-transfer-progress -Drevision=0.1.0 -Dchangelist=-SNAPSHOT --projects -:micrometer-certs-expiration-samples-spring-boot3,-:micrometer-certs-expiration-samples-micronaut4,-:micrometer-certs-expiration-samples-quarkus3
